"""initial

Revision ID: fd8cc00a7bd8
Revises: b63e040ced96
Create Date: 2025-10-01 16:49:22.664899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from core.database import Base, SessionLocal
from utils.permissions import add_permissions
from sqlalchemy.orm import Session


# revision identifiers, used by Alembic.
revision: str = 'fd8cc00a7bd8'
down_revision: Union[str, Sequence[str], None] = 'b63e040ced96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    bind = op.get_bind()
    session = Session(bind=bind)
    models = ["comments", "tasks", "teams"]
    add_permissions(models, session)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
